
const data = [
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3066",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3065",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3064",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3063",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3062",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3061",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3060",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3059",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3058",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3057",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3056",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3055",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3054",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3053",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3052",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3051",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3050",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3049",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3048",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3047",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3046",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3045",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "",
    dateannounced: "",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3044",
    source1: "",
    source2: "",
    source3: "",
    statecode: "",
    statepatientnumber: "",
    statuschangedate: "",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "03/04/2020",
    detectedcity: "",
    detecteddistrict: "",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "3043",
    source1: "https://twitter.com/PTI_News/status/1246097072761081856",
    source2: "",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "03/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2329",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2328",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2327",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2326",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2325",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2324",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2323",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2322",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2321",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2320",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2319",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2318",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2317",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2316",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2315",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2314",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2313",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2312",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2311",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2310",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2309",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "02/04/2020",
    detectedcity: "",
    detecteddistrict: "Mumbai",
    detectedstate: "Maharashtra",
    estimatedonsetdate: "",
    gender: "",
    nationality: "",
    notes: "",
    patientnumber: "2308",
    source1: "https://twitter.com/ANI/status/1245693514500804609",
    source2: "https://twitter.com/ANI/status/1245694253197488128",
    source3: "",
    statecode: "MH",
    statepatientnumber: "",
    statuschangedate: "02/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "11",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Kasaragod",
    detectedstate: "Kerala",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Contact transmission",
    patientnumber: "1876",
    source1: "https://twitter.com/PTI_News/status/1245330284574150656",
    source2:
      "https://www.facebook.com/permalink.php?story_fbid=159505228852647&id=100507158085788",
    source3: "",
    statecode: "KL",
    statepatientnumber: "",
    statuschangedate: "01/04/2020",
    typeoftransmission: "Local",
  },
  {
    agebracket: "32",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Kasaragod",
    detectedstate: "Kerala",
    estimatedonsetdate: "",
    gender: "F",
    nationality: "",
    notes: "Contact transmission",
    patientnumber: "1875",
    source1: "https://twitter.com/PTI_News/status/1245330284574150656",
    source2:
      "https://www.facebook.com/permalink.php?story_fbid=159505228852647&id=100507158085788",
    source3: "",
    statecode: "KL",
    statepatientnumber: "",
    statuschangedate: "01/04/2020",
    typeoftransmission: "Local",
  },
  {
    agebracket: "72",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Kasaragod",
    detectedstate: "Kerala",
    estimatedonsetdate: "",
    gender: "F",
    nationality: "",
    notes: "Contact transmission",
    patientnumber: "1874",
    source1: "https://twitter.com/PTI_News/status/1245330284574150656",
    source2:
      "https://www.facebook.com/permalink.php?story_fbid=159505228852647&id=100507158085788",
    source3: "",
    statecode: "KL",
    statepatientnumber: "",
    statuschangedate: "01/04/2020",
    typeoftransmission: "Local",
  },
  {
    agebracket: "52",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Kasaragod",
    detectedstate: "Kerala",
    estimatedonsetdate: "",
    gender: "F",
    nationality: "",
    notes: "Contact transmission",
    patientnumber: "1873",
    source1: "https://twitter.com/PTI_News/status/1245330284574150656",
    source2:
      "https://www.facebook.com/permalink.php?story_fbid=159505228852647&id=100507158085788",
    source3: "",
    statecode: "KL",
    statepatientnumber: "",
    statuschangedate: "01/04/2020",
    typeoftransmission: "Local",
  },
  {
    agebracket: "52",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Kasaragod",
    detectedstate: "Kerala",
    estimatedonsetdate: "",
    gender: "F",
    nationality: "",
    notes: "Contact transmission",
    patientnumber: "1872",
    source1: "https://twitter.com/PTI_News/status/1245330284574150656",
    source2:
      "https://www.facebook.com/permalink.php?story_fbid=159505228852647&id=100507158085788",
    source3: "",
    statecode: "KL",
    statepatientnumber: "",
    statuschangedate: "01/04/2020",
    typeoftransmission: "Local",
  },
  {
    agebracket: "18",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Kasaragod",
    detectedstate: "Kerala",
    estimatedonsetdate: "",
    gender: "F",
    nationality: "",
    notes: "Contact transmission",
    patientnumber: "1871",
    source1: "https://twitter.com/PTI_News/status/1245330284574150656",
    source2:
      "https://www.facebook.com/permalink.php?story_fbid=159505228852647&id=100507158085788",
    source3: "",
    statecode: "KL",
    statepatientnumber: "",
    statuschangedate: "01/04/2020",
    typeoftransmission: "Local",
  },
  {
    agebracket: "66",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Thiruvarur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1870",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P232",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "42",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Thiruvarur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "Myanmar",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1869",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P233",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "25",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Tirupathur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1868",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P194",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "38",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Tirupathur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1867",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P193",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "41",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Tirupathur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1866",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P192",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "39",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Tirupathur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1865",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P191",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "27",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Tirupathur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1864",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P190",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "40",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Tirupathur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1863",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P189",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "42",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Tirupathur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1862",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P188",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Tiruvannamalai",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1861",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P185",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Chennai",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1860",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P178",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Kancheepuram",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1859",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P187",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Kancheepuram",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "Indonesia",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1858",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P186",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "58",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Karur",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1857",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P234",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Thoothukkudi",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1856",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P126",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Thoothukkudi",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1855",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P125",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "40",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "Ilayankudi",
    detecteddistrict: "Sivaganga",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1854",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P137",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "38",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "Devakottai",
    detecteddistrict: "Sivaganga",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1853",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P136",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "48",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "Thirupathur",
    detecteddistrict: "Sivaganga",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1852",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P135",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "42",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "Thirupathur",
    detecteddistrict: "Sivaganga",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1851",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P134",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "48",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "Thirupathur",
    detecteddistrict: "Sivaganga",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1850",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P133",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Chengalpattu",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1849",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P184",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Chengalpattu",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1848",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P183",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Chengalpattu",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1847",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P182",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Chengalpattu",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1846",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P181",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Chengalpattu",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1845",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P180",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Chengalpattu",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1844",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P179",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Chengalpattu",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1843",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P177",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
  {
    agebracket: "",
    backupnotes: "",
    contractedfromwhichpatientsuspected: "E0",
    currentstatus: "Hospitalized",
    dateannounced: "01/04/2020",
    detectedcity: "",
    detecteddistrict: "Madurai",
    detectedstate: "Tamil Nadu",
    estimatedonsetdate: "",
    gender: "M",
    nationality: "",
    notes: "Attended Delhi Religious Conference",
    patientnumber: "1842",
    source1: "https://twitter.com/NHM_TN/status/1245332364563185664",
    source2: "",
    source3: "",
    statecode: "TN",
    statepatientnumber: "TN-P146",
    statuschangedate: "01/04/2020",
    typeoftransmission: "",
  },
];

let male = []
let female = []
let unknown = []

data.map((item) => {
    if (item.gender === "M") {
      male.push(item.gender);
    } else if (item.gender === "F") {
      female.push(item.gender);
    } else {
      unknown.push(item.gender);
    }
  });


console.log('Female - ' +female.length)
console.log('Male - ' +male.length)
console.log('Unknown - ' +unknown.length)

